[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ztgateway"
version = "0.3.0"
description = "Zero Touch Provisioning Gateway"
authors = [{name = "Danila Derevyanko"}]
dependencies = [
    "netifaces>=0.11.0",
    "redis>=4.5.0",
    "pyyaml>=6.0",
]

[project.scripts]
ztgateway = "ztgateway.cli:main"

[tool.setuptools.packages.find]
where = ["src"]